CREATE TABLE [Aircraft](
	[ID] [int] IDENTITY(1,1) NOT NULL,
    [Name] [nvarchar] (20) NOT NULL,
	[FuelConsumption] [float] NOT NULL,
	[TakeoffEffort] [float] NOT NULL
 CONSTRAINT [PK_Aircraft] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

